//
// Created by William Méroz-Moreau on 2026-07-30.
//

#ifndef DATABASE_ENGINE_FROM_SCRATCH_STATEMENTTYPE_H
#define DATABASE_ENGINE_FROM_SCRATCH_STATEMENTTYPE_H

enum class StatementType { STATEMENT_INSERT, STATEMENT_SELECT };

#endif //DATABASE_ENGINE_FROM_SCRATCH_STATEMENTTYPE_H
